added legacy/ to .gitignore , excluded the .venv pre-commit hooks checks , and removed __init__.py from the project’s root directory/ so it's not an importable Python package anymore; can now run the test suite with bare ============================= test session starts ============================== platform darwin -- Python 3.12.7, pytest-9.0.2, pluggy-1.6.0 rootdir: /Users/ionut/Desktop/projects/backtester plugins: approvaltests-19.1.1, cov-7.1.0, anyio-4.13.0 collected 111 items
tests/test_compute_average.py F......                                    [  6%]
tests/test_data_loader.py FFFFF                                          [ 10%]
tests/test_main.py ..................................................... [ 58%]
.........                                                                [ 66%]
tests/test_mean_rev_signal.py FFF                                        [ 69%]
tests/test_performance_metrics.py .............................          [ 95%]
tests/test_process_1_day.py FF                                           [ 97%]
tests/test_trend_signal.py FFF                                           [100%]

=================================== FAILURES ===================================
______________________ TestComputeAverage.test_empty_list ______________________

self = <tests.test_compute_average.TestComputeAverage testMethod=test_empty_list>

    def test_empty_list(self):
>       with self.assertRaises(ZeroDivisionError):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E       AssertionError: ZeroDivisionError not raised

tests/test_compute_average.py:14: AssertionError
_____________________ TestDataLoaderMethods.test_2_row_csv _____________________

self = <tests.test_data_loader.TestDataLoaderMethods testMethod=test_2_row_csv>

    def test_2_row_csv(self):
        # create a temporary file that only contains 2 rows => average and nextDayOpeningPrice are both None during first 2 days
        with tempfile.NamedTemporaryFile(mode="w", suffix=".csv", delete=False) as f:
            f.write("Date, Open, High, Low, Close, Adj Close, Volume\n")
            f.write("2026-01-01, 5, 5, 5, 5, 5, 1000\n")
            f.write("2026-01-02, 6, 6, 6, 6, 6, 1000")
            # store the full path of this temporary file so we can reopen/read it later after leaving the with block
            temp_path_created_file = f.name
        # the file is now closed, but the generator can open it because we've stored its path as a string inside temp_path_created_file
        # we need to make sure that the temp file gets deleted no matter what the outcome
        try:
            # check that generator asserts correct tuples for days 1 and 2
>           generator = dl.read_ticker_csv(
                        ^^^^^^^^^^^^^^^^^^
                temp_path_created_file, 100, verbose_run=False
            )
E           AttributeError: module 'data_loading.data_loader' has no attribute 'read_ticker_csv'

tests/test_data_loader.py:64: AttributeError
_____________________ TestDataLoaderMethods.test_empty_csv _____________________

self = <tests.test_data_loader.TestDataLoaderMethods testMethod=test_empty_csv>

    def test_empty_csv(self):
        # create a temporary file that is empty
        with tempfile.NamedTemporaryFile(mode="w", suffix=".csv", delete=False) as f:
            # nothing to write inside it other than the header (that is skipped)
            f.write("Date, Open, High, Low, Close, Volume\n")
            # store the full path of this temporary file so we can reopen/read it later after leaving the with block
            temp_path_created_file = f.name
        # the file is now closed, but the generator can open it because we've stored its path as a string inside temp_path_created_file
        # we need to make sure that the temp file that we created gets deleted no matter what the outcome
        try:
            # empty csv file => generator can't yield any tuples
>           generator = dl.read_ticker_csv(
                        ^^^^^^^^^^^^^^^^^^
                temp_path_created_file, 100, verbose_run=False
            )
E           AttributeError: module 'data_loading.data_loader' has no attribute 'read_ticker_csv'

tests/test_data_loader.py:40: AttributeError
______________ TestDataLoaderMethods.test_inconsistent_data_type _______________

self = <tests.test_data_loader.TestDataLoaderMethods testMethod=test_inconsistent_data_type>

    def test_inconsistent_data_type(self):
        # create a temporary file with incorrect structure that you can test on for the edge case
        with tempfile.NamedTemporaryFile(mode="w", suffix=".csv", delete=False) as f:
            f.write("Date, Open, High, Low, Close, Adj Close, Volume\n")
            f.write("2026-01-01, 6, 6, 6, 6, 6, 1000\n")
            f.write("2026-01-01, 10, 10, 10, 10, 10, 1000\n")
            # string type in place of numeric closing price
            f.write("2026-01-01, 6, 6, 6, 'error', 6, 1000\n")
            # store the full path of this temporary file so we can reopen/read it later after leaving the with block
            temp_path_created_file = f.name
        # the file is now closed, but the generator can open it because we've stored its path as a string inside temp_path_created_file
        # we need to make sure that the temp file gets deleted no matter what the outcome
        try:
            # generator yields values from the temporarily created tmp.csv file
>           generator = dl.read_ticker_csv(
                        ^^^^^^^^^^^^^^^^^^
                temp_path_created_file, 100, verbose_run=False
            )
E           AttributeError: module 'data_loading.data_loader' has no attribute 'read_ticker_csv'

tests/test_data_loader.py:120: AttributeError
___________________ TestDataLoaderMethods.test_malformed_csv ___________________

self = <tests.test_data_loader.TestDataLoaderMethods testMethod=test_malformed_csv>

    def test_malformed_csv(self):
        # create a temporary file with malformed structure (too many fields) that you can test on for the edge case
        with tempfile.NamedTemporaryFile(mode="w", suffix=".csv", delete=False) as f:
            f.write("Date, Open, High, Low, Close, Adj Close, Volume\n")
            f.write("2026-01-01, 6, 6, 6, 6, 6, 1000\n")
            # closing price index missing => float(line[4]) will raise an error
            f.write("2026-01-01, 6, 6, 6\n")
            # store the full path of this temporary file so we can reopen/read it later after leaving the with block
            temp_path_created_file = f.name
        # the file is now closed, but the generator can open it because we've stored its path as a string inside temp_path_created_file
        # we need to make sure that the temp file gets deleted no matter what the outcome
        try:
            # generator yields values from the temporary file
>           generator = dl.read_ticker_csv(
                        ^^^^^^^^^^^^^^^^^^
                temp_path_created_file, 100, verbose_run=False
            )
E           AttributeError: module 'data_loading.data_loader' has no attribute 'read_ticker_csv'

tests/test_data_loader.py:92: AttributeError
____________________ TestDataLoaderMethods.test_normal_csv _____________________

self = <tests.test_data_loader.TestDataLoaderMethods testMethod=test_normal_csv>

    def test_normal_csv(self):
        # holds tuples representing each day's values
>       generator = dl.read_ticker_csv("data/5_day_input.csv", 100, verbose_run=False)
                    ^^^^^^^^^^^^^^^^^^
E       AttributeError: module 'data_loading.data_loader' has no attribute 'read_ticker_csv'

tests/test_data_loader.py:15: AttributeError
_________________ TestMeanRevSignal.test_correct_printed_text __________________

self = <tests.test_mean_rev_signal.TestMeanRevSignal testMethod=test_correct_printed_text>

    def test_correct_printed_text(self):

        # capture printed stdout in an in-memory buffer, then compare it to the expected formatted output
        # no pending action case
        with contextlib.redirect_stdout(io.StringIO()) as buffer:
>           mrv.mean_rev_step(
                1,
                "2026-05-01",
                10,
                5.5,
                10,
                100,
                100,
                "",
                20,
                0.005,
                0.0005,
                0,
                10,
                11,
                0,
            )
E           TypeError: mean_rev_step() missing 3 required positional arguments: 'entryPriceMeanReversion', 'exitPriceMeanReversion', and 'profitMeanReversion'

tests/test_mean_rev_signal.py:148: TypeError
____________________ TestMeanRevSignal.test_invalid_inputs _____________________

self = <tests.test_mean_rev_signal.TestMeanRevSignal testMethod=test_invalid_inputs>

    def test_invalid_inputs(self):

        # incorrect nb of arguments passed in
        with self.assertRaises(TypeError):
            mrv.mean_rev_step(
                1, "2026-05-01", 10, 5.5, 10, 100, 100, "", 20, 0.005, 0.0005, 0, 10, 11
            )

        # checking if pending_action is a string
        with self.assertRaises(TypeError):
            mrv.mean_rev_step(
                1,
                "2026-05-01",
                10,
                5.5,
                10,
                100,
                100,
                55,
                20,
                0.005,
                0.0005,
                0,
                10,
                11,
                0,
            )

        # checking that pending_action is in {"BUY", "SELL", "HOLD", ""}
        with self.assertRaises(ValueError):
>           mrv.mean_rev_step(
                1,
                "2026-05-01",
                10,
                5.5,
                10,
                100,
                100,
                "invalid",
                20,
                0.005,
                0.0005,
                0,
                10,
                11,
                0,
            )
E           TypeError: mean_rev_step() missing 3 required positional arguments: 'entryPriceMeanReversion', 'exitPriceMeanReversion', and 'profitMeanReversion'

tests/test_mean_rev_signal.py:326: TypeError
__________________ TestMeanRevSignal.test_main_logic_behavior __________________

self = <tests.test_mean_rev_signal.TestMeanRevSignal testMethod=test_main_logic_behavior>

    def test_main_logic_behavior(self):

        # no pending action
        self.assertEqual(
>           mrv.mean_rev_step(
                1,
                "2026-05-01",
                10,
                5.5,
                10,
                100,
                100,
                "",
                20,
                0.005,
                0.0005,
                0,
                10,
                11,
                0,
            ),
            (0, 0, 10, 11, 100, 100, "SELL"),
        )
E       TypeError: mean_rev_step() missing 3 required positional arguments: 'entryPriceMeanReversion', 'exitPriceMeanReversion', and 'profitMeanReversion'

tests/test_mean_rev_signal.py:17: TypeError
____________________ TestProcessDay.test_invalid_data_type _____________________

self = <tests.test_process_1_day.TestProcessDay testMethod=test_invalid_data_type>

    def test_invalid_data_type(self):
        # checking that trendMethod is a boolean
        with self.assertRaises(TypeError):
            process_1_day.process_one_day(
                1,
                "2026-05-01",
                10,
                5.5,
                10,
                100,
                100,
                "SELL",
                20,
                0.005,
                0.0005,
                "False",
                0,
                10,
                11,
                0,
                2,
                10,
                11,
                0,
            )
        # checking that pending_action is a string data type
        with self.assertRaises(TypeError):
            process_1_day.process_one_day(
                1,
                "2026-05-01",
                10,
                5.5,
                10,
                100,
                100,
                True,
                20,
                0.005,
                0.0005,
                False,
                0,
                10,
                11,
                0,
                2,
                10,
                11,
                0,
            )
        # pending_action is a string data type but is not inside {BUY, SELL, HOLD, ''}
        with self.assertRaises(ValueError):
>           process_1_day.process_one_day(
                1,
                "2026-05-01",
                10,
                5.5,
                10,
                100,
                100,
                "incorrect string",
                20,
                0.005,
                0.0005,
                False,
                0,
                10,
                11,
                0,
                2,
                10,
                11,
                0,
            )
E           TypeError: process_one_day() missing 3 required positional arguments: 'entryPriceMeanReversion', 'exitPriceMeanReversion', and 'profitMeanReversion'

tests/test_process_1_day.py:162: TypeError
____________________ TestProcessDay.test_valid_redirection _____________________

self = <tests.test_process_1_day.TestProcessDay testMethod=test_valid_redirection>

    def test_valid_redirection(self):
        self.assertEqual(
>           process_1_day.process_one_day(
                1,
                "2026-05-01",
                10,
                5.5,
                10,
                100,
                100,
                "",
                20,
                0.005,
                0.0005,
                True,
                0,
                10,
                11,
                0,
                0,
                10,
                10,
                0,
            ),
            (0, 0, 10, 11, 100, 100, "BUY"),
        )
E       TypeError: process_one_day() missing 3 required positional arguments: 'entryPriceMeanReversion', 'exitPriceMeanReversion', and 'profitMeanReversion'

tests/test_process_1_day.py:10: TypeError
__________________ TestTrendSignal.test_correct_printed_text ___________________

self = <tests.test_trend_signal.TestTrendSignal testMethod=test_correct_printed_text>

    def test_correct_printed_text(self):

        # capture printed stdout in an in-memory buffer, then compare it to the expected formatted output
        # no pending action case
        with contextlib.redirect_stdout(io.StringIO()) as buffer:
>           ts.trend_step(
                1,
                "2026-05-01",
                10,
                5.5,
                10,
                100,
                100,
                "",
                20,
                0.005,
                0.0005,
                0,
                10,
                11,
                0,
            )
E           TypeError: trend_step() missing 3 required positional arguments: 'entryPriceTrend', 'exitPriceTrend', and 'profitTrend'

tests/test_trend_signal.py:148: TypeError
_____________________ TestTrendSignal.test_invalid_inputs ______________________

self = <tests.test_trend_signal.TestTrendSignal testMethod=test_invalid_inputs>

    def test_invalid_inputs(self):

        # incorrect nb of arguments passed in
        with self.assertRaises(TypeError):
            ts.trend_step(
                1, "2026-05-01", 10, 5.5, 10, 100, 100, "", 20, 0.005, 0.0005, 0, 10, 11
            )

        # checking if pending_action is a string
        with self.assertRaises(TypeError):
            ts.trend_step(
                1,
                "2026-05-01",
                10,
                5.5,
                10,
                100,
                100,
                55,
                20,
                0.005,
                0.0005,
                0,
                10,
                11,
                0,
            )

        # checking that pending_action is in {"BUY", "SELL", "HOLD", ""}
        with self.assertRaises(ValueError):
>           ts.trend_step(
                1,
                "2026-05-01",
                10,
                5.5,
                10,
                100,
                100,
                "invalid",
                20,
                0.005,
                0.0005,
                0,
                10,
                11,
                0,
            )
E           TypeError: trend_step() missing 3 required positional arguments: 'entryPriceTrend', 'exitPriceTrend', and 'profitTrend'

tests/test_trend_signal.py:326: TypeError
___________________ TestTrendSignal.test_main_logic_behavior ___________________

self = <tests.test_trend_signal.TestTrendSignal testMethod=test_main_logic_behavior>

    def test_main_logic_behavior(self):

        # no pending action
        self.assertEqual(
>           ts.trend_step(
                1,
                "2026-05-01",
                10,
                5.5,
                10,
                100,
                100,
                "",
                20,
                0.005,
                0.0005,
                0,
                10,
                11,
                0,
            ),
            (0, 0, 10, 11, 100, 100, "BUY"),
        )
E       TypeError: trend_step() missing 3 required positional arguments: 'entryPriceTrend', 'exitPriceTrend', and 'profitTrend'

tests/test_trend_signal.py:17: TypeError
=============================== warnings summary ===============================
tests/test_compute_average.py::TestComputeAverage::test_empty_list
  /Users/ionut/Desktop/projects/backtester/.venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
    return _methods._mean(a, axis=axis, dtype=dtype,

tests/test_compute_average.py::TestComputeAverage::test_empty_list
  /Users/ionut/Desktop/projects/backtester/.venv/lib/python3.12/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
    ret = ret.dtype.type(ret / rcount)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_compute_average.py::TestComputeAverage::test_empty_list - A...
FAILED tests/test_data_loader.py::TestDataLoaderMethods::test_2_row_csv - Att...
FAILED tests/test_data_loader.py::TestDataLoaderMethods::test_empty_csv - Att...
FAILED tests/test_data_loader.py::TestDataLoaderMethods::test_inconsistent_data_type
FAILED tests/test_data_loader.py::TestDataLoaderMethods::test_malformed_csv
FAILED tests/test_data_loader.py::TestDataLoaderMethods::test_normal_csv - At...
FAILED tests/test_mean_rev_signal.py::TestMeanRevSignal::test_correct_printed_text
FAILED tests/test_mean_rev_signal.py::TestMeanRevSignal::test_invalid_inputs
FAILED tests/test_mean_rev_signal.py::TestMeanRevSignal::test_main_logic_behavior
FAILED tests/test_process_1_day.py::TestProcessDay::test_invalid_data_type - ...
FAILED tests/test_process_1_day.py::TestProcessDay::test_valid_redirection - ...
FAILED tests/test_trend_signal.py::TestTrendSignal::test_correct_printed_text
FAILED tests/test_trend_signal.py::TestTrendSignal::test_invalid_inputs - Typ...
FAILED tests/test_trend_signal.py::TestTrendSignal::test_main_logic_behavior
================== 14 failed, 97 passed, 2 warnings in 1.50s ===================